site_name: Tự học Khoa học máy tính
site_description: vozer vozer vozer vozer vozer vozer vozer vozer vozer vozer 
site_author: duykhanh471
repo_url: https://github.com/daihocmo/khoa-hoc-may-tinh
repo_name: Đóng góp cho trang trên Github

nav:
  - 'Trang chủ': 'index.md'
  - 'Hướng dẫn tự học':
    - 'Đôi chút về lập trình': 'bat-dau.md'
    - 'Ghi nhớ': 'ghi-nho.md'
    - 'Nhật ký code': 'nhat-ky-code.md'
    - 'Lên kế hoạch cho dự án': 'cach-len-ke-hoach.md'
  - 'Giáo trình tự học':
    - 'Hướng dẫn chính': 'khmt.md'
    - 'CTDL & Giải thuật': 'ctdl-gt.md'
    - 'Toán': 'toan.md'
    
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  icon:
    repo: fontawesome/brands/github
  language: vi

markdown_extensions:
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      
      
plugins:
  - search
  - open-in-new-tab
  
extra:
  generator: false
