site_name: Không học máy tính
site_description: vozer vozer vozer vozer vozer vozer vozer vozer vozer vozer 
site_author: duykhanh471
repo_url: https://github.com/daihocmo/khoa-hoc-may-tinh
repo_name: Đóng góp cho trang trên Github

nav:
  - 'Trang chủ': 'index.md'
  - 'Fullstack': 'full-stack.md'
  - 'Khoa học máy tính': 'teach-yourself-cs.md'  
  - 'IT English': 'tieng-anh-it.md'
  - 'Tài nguyên học': 'resources.md'
  - 'Youtube': 'youtube.md'
  - 'Các hướng dẫn khác':
    - 'Cách lên kế hoạch': 'cach-len-ke-hoach.md'
    - 'Tư duy lập trình': 'tu-duy-lap-trinh.md'
    
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  language: vi

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      
plugins:
  - search
  - open-in-new-tab
  
extra:
  generator: false
