site_name: Không học máy tính
site_description: vozer vozer vozer vozer vozer vozer vozer vozer vozer vozer 
site_author: duykhanh471
repo_url: https://github.com/daihocmo/khoa-hoc-may-tinh
repo_name: Đóng góp cho trang trên Github

nav:
  - 'Trang chủ': 'index.md'
  - 'Hướng dẫn tự học':
    - 'Bắt đầu học lập trình': 'truoc-khi-bat-dau-vi.md'
    - 'Janki - Phần 1': 'janki1-vi.md'
    - 'Janki - Phần 2': 'janki2-vi.md'
  - 'Hướng dẫn tự học KHMT':
    - 'TYCS': 'khmt.md'
    - 'Khoa học máy tính': 'khmt-vi.md'
  - 'Các môn học':
    - 'Programming': 'programming.md'
    - 'Kiến trúc máy tính': 'architecture.md'
    - 'CTDL & Giải thuật': 'algorithms.md'
    - 'Toán': 'math.md'
    - 'Hệ điều hành': 'os.md'
    - 'Mạng máy tính': 'computer-networking.md'
    - 'Cơ sở dữ liệu': 'database.md'
    - 'Languages and Compilers': 'languages-and-compilers.md'
    - 'Hệ thống phân tán': 'distributed-systems.md'
  - 'Định hướng':
    - 'Fullstack': 'fullstack.md'
    - 'DevOps': 'devops.md'
  - 'Các hướng dẫn khác':
    - 'Cách lên kế hoạch': 'cach-len-ke-hoach.md'
    - 'Tư duy lập trình': 'tu-duy-lap-trinh.md'
    - 'Nhật ký lập trình': 'code-diary.md'
    - 'Webdev101': 'webdev101.md'
  - 'IT English': 'tieng-anh-it.md'
  - 'Tài nguyên học': 'resources.md'

    
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  icon:
    repo: fontawesome/brands/github
  language: vi

plugins:
  - search
  - open-in-new-tab
  
extra:
  generator: false
