site_name: Không học máy tính
site_description: vozer vozer vozer vozer vozer vozer vozer vozer vozer vozer 
site_author: duykhanh471
repo_url: https://github.com/daihocmo/khoa-hoc-may-tinh
repo_name: Đóng góp cho trang trên Github

nav:
  - 'Trang chủ': 'index.md'
  - 'Hướng dẫn bắt đầu':
    - 'Bắt đầu học lập trình': 'truoc-khi-bat-dau.md'
    - 'Janki - Phần 1': 'janki1.md'
    - 'Janki - Phần 2': 'janki2.md'
  - 'Fullstack': 'fullstack.md'
  - 'Khoa học máy tính': 
    - 'Lộ trình chính': 'khmt.md'
    - 'Programming': 'programming.md'
    - 'Kiến trúc máy tính': 'architecture.md'
    - 'CTDL & Giải thuật': 'algorithms.md'
    - 'Toán': 'math.md'
    - 'Hệ điều hành': 'os.md'
    - 'Mạng máy tính': 'computer-networking.md'
    - 'Cơ sở dữ liệu': 'database.md'
    - 'Languages and Compilers': 'languages-and-compilers.md'
    - 'Hệ thống phân tán': 'distributed-systems.md'
  - 'Các hướng dẫn khác':
    - 'Cách lên kế hoạch': 'cach-len-ke-hoach.md'
    - 'Tư duy lập trình': 'tu-duy-lap-trinh.md'
    - 'Nhật ký lập trình': 'code-diary.md'
    - 'Webdev101': 'webdev101.md'
  - 'IT English': 'tieng-anh-it.md'
  - 'Tài nguyên học': 'resources.md'
  - 'Youtube': 'youtube.md'

    
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  icon:
    repo: fontawesome/brands/github
  language: vi

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      
plugins:
  - search
  - open-in-new-tab
  
extra:
  generator: false
