site_name: Tự học Khoa học máy tính
site_description: vozer vozer vozer vozer vozer vozer vozer vozer vozer vozer 
site_author: duykhanh471
repo_url: https://github.com/daihocmo/khoa-hoc-may-tinh
repo_name: Đóng góp cho trang trên Github

nav:
  - 'Trang chủ': 'index.md'
  - 'Hướng dẫn tự học':
    - 'Bắt đầu': 'bat-dau.md'
    - 'Ghi nhớ': 'ghi-nho.md'
    - 'Nhật ký code': 'nhat-ky-code.md'
    - 'Tư duy lập trình': 'tu-duy-lap-trinh.md'
    - 'Đừng làm dự án nữa': 'cach-len-ke-hoach.md'
  - 'Giáo trình tự học':
    - 'TYCS': 'khmt.md'
    - 'Giáo trình chính': 'khmt-vi.md'
    - 'Lập trình': 'programming.md'
    - 'Kiến trúc máy tính': 'architecture.md'
    - 'CTDL & Giải thuật': 'algorithms.md'
    - 'Toán': 'math.md'
    - 'Hệ điều hành': 'os.md'
    - 'Mạng máy tính': 'computer-networking.md'
    - 'Cơ sở dữ liệu': 'database.md'
    - 'Trình biên dịch': 'languages-and-compilers.md'
    - 'Hệ thống phân tán': 'distributed-systems.md'
  - 'Định hướng chuyên môn':
    - 'Lựa chọn': 'lua-chon.md'
    - 'Fullstack': 'fullstack.md'
    - 'DevOps': 'devops.md'
  - 'Tự học Tiếng Anh': 'tieng-anh-it.md'
  - 'Tài nguyên học': 'resources.md'

    
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  icon:
    repo: fontawesome/brands/github
  language: vi

plugins:
  - search
  - open-in-new-tab
  
extra:
  generator: false
